spring:
  application:
    name: pattern.forge
  datasource:
    url: jdbc:postgresql://localhost:5432/patternforge
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.xml